/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EpubRouteImport } from './routes/epub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeechOptimizeRouteImport } from './routes/speech/optimize'

const EpubRoute = EpubRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechOptimizeRoute = SpeechOptimizeRouteImport.update({
  id: '/speech/optimize',
  path: '/speech/optimize',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/epub' | '/speech/optimize'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/epub' | '/speech/optimize'
  id: '__root__' | '/' | '/epub' | '/speech/optimize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpubRoute: typeof EpubRoute
  SpeechOptimizeRoute: typeof SpeechOptimizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/epub': {
      id: '/epub'
      path: '/epub'
      fullPath: '/epub'
      preLoaderRoute: typeof EpubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/optimize': {
      id: '/speech/optimize'
      path: '/speech/optimize'
      fullPath: '/speech/optimize'
      preLoaderRoute: typeof SpeechOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpubRoute: EpubRoute,
  SpeechOptimizeRoute: SpeechOptimizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
