/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as EpubRouteImport } from './routes/epub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpeechOptimizeRouteImport } from './routes/speech/optimize'
import { Route as MockupsStudioRouteImport } from './routes/mockups/studio'
import { Route as MockupsConsoleRouteImport } from './routes/mockups/console'
import { Route as MockupsAuroraRouteImport } from './routes/mockups/aurora'

const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const EpubRoute = EpubRouteImport.update({
  id: '/epub',
  path: '/epub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeechOptimizeRoute = SpeechOptimizeRouteImport.update({
  id: '/speech/optimize',
  path: '/speech/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsStudioRoute = MockupsStudioRouteImport.update({
  id: '/mockups/studio',
  path: '/mockups/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsConsoleRoute = MockupsConsoleRouteImport.update({
  id: '/mockups/console',
  path: '/mockups/console',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupsAuroraRoute = MockupsAuroraRouteImport.update({
  id: '/mockups/aurora',
  path: '/mockups/aurora',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/library': typeof LibraryRoute
  '/mockups/aurora': typeof MockupsAuroraRoute
  '/mockups/console': typeof MockupsConsoleRoute
  '/mockups/studio': typeof MockupsStudioRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/library': typeof LibraryRoute
  '/mockups/aurora': typeof MockupsAuroraRoute
  '/mockups/console': typeof MockupsConsoleRoute
  '/mockups/studio': typeof MockupsStudioRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epub': typeof EpubRoute
  '/library': typeof LibraryRoute
  '/mockups/aurora': typeof MockupsAuroraRoute
  '/mockups/console': typeof MockupsConsoleRoute
  '/mockups/studio': typeof MockupsStudioRoute
  '/speech/optimize': typeof SpeechOptimizeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epub'
    | '/library'
    | '/mockups/aurora'
    | '/mockups/console'
    | '/mockups/studio'
    | '/speech/optimize'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epub'
    | '/library'
    | '/mockups/aurora'
    | '/mockups/console'
    | '/mockups/studio'
    | '/speech/optimize'
  id:
    | '__root__'
    | '/'
    | '/epub'
    | '/library'
    | '/mockups/aurora'
    | '/mockups/console'
    | '/mockups/studio'
    | '/speech/optimize'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpubRoute: typeof EpubRoute
  LibraryRoute: typeof LibraryRoute
  MockupsAuroraRoute: typeof MockupsAuroraRoute
  MockupsConsoleRoute: typeof MockupsConsoleRoute
  MockupsStudioRoute: typeof MockupsStudioRoute
  SpeechOptimizeRoute: typeof SpeechOptimizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epub': {
      id: '/epub'
      path: '/epub'
      fullPath: '/epub'
      preLoaderRoute: typeof EpubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speech/optimize': {
      id: '/speech/optimize'
      path: '/speech/optimize'
      fullPath: '/speech/optimize'
      preLoaderRoute: typeof SpeechOptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/studio': {
      id: '/mockups/studio'
      path: '/mockups/studio'
      fullPath: '/mockups/studio'
      preLoaderRoute: typeof MockupsStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/console': {
      id: '/mockups/console'
      path: '/mockups/console'
      fullPath: '/mockups/console'
      preLoaderRoute: typeof MockupsConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockups/aurora': {
      id: '/mockups/aurora'
      path: '/mockups/aurora'
      fullPath: '/mockups/aurora'
      preLoaderRoute: typeof MockupsAuroraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpubRoute: EpubRoute,
  LibraryRoute: LibraryRoute,
  MockupsAuroraRoute: MockupsAuroraRoute,
  MockupsConsoleRoute: MockupsConsoleRoute,
  MockupsStudioRoute: MockupsStudioRoute,
  SpeechOptimizeRoute: SpeechOptimizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
